import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { Event } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const NavBar = () => {
  const user = useUser()

  return <nav className="flex flex-row items-center justify-between p-5 w-full h-10 bg-slate-300">
    <div>
      { user?.isSignedIn ? (
        <SignOutButton />
      ) : (
        <SignInButton />
      )}
    </div>
    <div className="flex flex-row gap-5">
    <Link href="/"> Home </Link>
    <Link href="/"> Events </Link>
    </div>
  </nav>
}

const EventItem = ({ event }: { event: Event }) => {
  return (
    <div className="flex flex-row w-full">
      <div> {event.title} - {event.category} - {event.value} </div>
    </div>
  )
}

const Home: NextPage = () => {

  const { data: futureEvents, isLoading: futureEventsLoading } = api.events.getFutureEvents.useQuery()
  const { data: eventData, isLoading: eventsLoading } = api.events.getUserEvents.useQuery()

  if (eventsLoading || futureEventsLoading) {
    return <div>Loading</div>
  }

  if (!eventData || !futureEvents) {
    return <div>Error</div>
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col min-h-screen flex-col items-center justify-center">
        <NavBar />
        <div className="flex-1">
          { eventData.map(event => <EventItem key={event.id} event={event} />) }
          <div>Opportunities</div>
          { futureEvents.map(event => <EventItem key={event.id} event={event} />) }
        </div>
      </main>
    </>
  );
};

export default Home;
